{% set name = "curifactory" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/curifactory-{{ version }}.tar.gz
  sha256: 5cb4b5d86cd553d58be67d402303865ce264bcdbb53ac3534d7395f19fe488a3

build:
  entry_points:
    - experiment=curifactory.experiment:main
    - curifactory=curifactory.project:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - ipynb-py-convert
    - python-graphviz
    - matplotlib-base
    - psutil
    - rich

test:
  imports:
    - curifactory
  commands:
    - pip check
    - experiment --help
    - curifactory --help
  requires:
    - pip

about:
  home: https://github.com/ORNL/curifactory
  summary: An experiment workflow and organization tool
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://ornl.github.io/curifactory/latest/index.html
  dev_url: https://github.com/ORNL/curifactory

extra:
  recipe-maintainers:
    - mbadams5
    - WildfireXIII
    - stewartsl
    - jasonmhite
