{% set name = "curifactory" %}
{% set version = "0.20.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/curifactory-{{ version }}.tar.gz
  sha256: aa616021130826d1b6da0125c997b94a8794eb0fcbf02a80c961ed49fcac7caf

build:
  entry_points:
    - experiment=curifactory.cli:main
    - curifactory=curifactory.project:main
    - cf=curifactory.experimental.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - ipynb-py-convert
    - python-graphviz
    - matplotlib-base
    - psutil
    - rich
    - argcomplete
    - duckdb

test:
  imports:
    - curifactory
  commands:
    - pip check
    - experiment --help
    - curifactory --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ORNL/curifactory
  summary: An experiment workflow and organization tool
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://ornl.github.io/curifactory/latest/index.html
  dev_url: https://github.com/ORNL/curifactory

extra:
  recipe-maintainers:
    - WarmCyan
    - mbadams5
    - stewartsl
