{% set name = "curifactory" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/curifactory-{{ version }}.tar.gz
  sha256: 4c0580a3f1741296d2794473a0b2da84c13f603f5fb94bef36ed62f0b8d79f48

build:
  entry_points:
    - experiment=curifactory.cli:main
    - curifactory=curifactory.project:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - ipynb-py-convert
    - python-graphviz
    - matplotlib-base
    - psutil
    - rich
    - argcomplete

test:
  imports:
    - curifactory
  commands:
    - pip check
    - experiment --help
    - curifactory --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ORNL/curifactory
  summary: An experiment workflow and organization tool
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://ornl.github.io/curifactory/latest/index.html
  dev_url: https://github.com/ORNL/curifactory

extra:
  recipe-maintainers:
    - WarmCyan
    - mbadams5
    - stewartsl
