{% set name = "curifactory" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/curifactory-{{ version }}.tar.gz
  sha256: cfaa1ef2b5d1668a9054ce2f9ce178f61fcfa21b47d25a77859984d76800ac68

build:
  entry_points:
    - experiment=curifactory.experiment:main
    - curifactory=curifactory.project:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas
    - ipynb-py-convert
    - python-graphviz
    - matplotlib-base
    - psutil
    - rich
    - argcomplete

test:
  imports:
    - curifactory
  commands:
    - pip check
    - experiment --help
    - curifactory --help
  requires:
    - pip

about:
  home: https://github.com/ORNL/curifactory
  summary: An experiment workflow and organization tool
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://ornl.github.io/curifactory/latest/index.html
  dev_url: https://github.com/ORNL/curifactory

extra:
  recipe-maintainers:
    - WildfireXIII
    - mbadams5
    - stewartsl
    - jasonmhite
